on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Packages CI

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      # You need to explicitly output the tag name and release_created for each package
      # This assumes your release-please-config.json and .release-please-manifest.json
      # are set up to handle multiple packages and will output these.
      "packages/core--tag_name": ${{ steps.release.outputs['packages/core--tag_name'] }}
      "packages/core--release_created": ${{ steps.release.outputs['packages/core--release_created'] }}
      # Add more outputs for other packages here

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  release-core:
    if: ${{ needs.release-please.outputs['packages/core--release_created'] == 'true' }}
    uses: ./.github/workflows/_template-package.cd.yaml
    needs: release-please
    with:
      package_path: core
      package_npm_name: "@qfetch/core"
      package_tag_name: ${{ needs.release-please.outputs['packages/core--tag_name'] }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

