name: core package

on:
  pull_request:
    paths:
      - packages/core/**
      - .github/workflows/core.ci.yaml
      - .github/workflows/_template-package.ci.yaml
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/_template-package.ci.yaml
    with:
      package_path: core
      package_npm_name: "@qfetch/core"

